## 네이버 검색 API 서비스

### 블로그

#### xml로 가져오기

In [3]:
# 네이버 검색 API예제는 블로그를 비롯 전문자료까지 호출방법이 동일하므로 blog검색만 대표로 예제를 올렸습니다.
# 네이버 검색 Open API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
#url = "https://openapi.naver.com/v1/search/blog?query=" + query # json 결과
url = "https://openapi.naver.com/v1/search/blog.xml?query=" + query # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

검색빅데이터
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Naver Open API - blog ::&apos;빅데이터&apos;</title><link>https://search.naver.com</link><description>Naver Search Result</description><lastBuildDate>Thu, 28 Jul 2022 10:39:29 +0900</lastBuildDate><total>1144657</total><start>1</start><display>10</display><item><title>&lt;b&gt;빅데이터&lt;/b&gt;전문가 준비를 위한 체계적인 방법</title><link>https://blog.naver.com/nam8853nam?Redirect=Log&amp;logNo=222802704648</link><description>그 중에서도 주목해 볼만한 분야가 바로 ‘&lt;b&gt;빅데이터&lt;/b&gt;’ 라고 생각했어요. 기업이 이익을 창출하기... 이런 점들을 고려했을 때 1) 영업, 2) 컨설팅, 3) 제조 분야 모두 통틀어서 데이터 분석이 정말 중요한 부분을... </description><bloggername>율맘 스토리</bloggername><bloggerlink>https://blog.naver.com/nam8853nam</bloggerlink><postdate>20220707</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;분석기사 실기 준비를 위한 학습루틴</title><link>https://blog.naver.com/parkrapp?Redirect=Log&amp;logNo=222753783578</link><description>안녕하세요, 오늘은 제가 도전한 &lt;b&gt;빅데이터&lt;/b&gt;분석기사에 대한 정보를 많은 분과 나누고 싶어 이야기를... &lt;b&gt;빅데이터&lt;/b&gt;를 이해하고 이를 분석, 수집, 저장 등의 시각화를 수행하는 실무자 역할을 하는 분석기사는... </description><bloggername>황금빛 쭈롱월드</bloggername><bloggerlink>https://blog.naver.com/parkrapp</bloggerlink><postdate>20220531</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;전문가 공부했던 과정</title><link>https://blog.naver.com/kmin4015?Redirect=Log&amp;logNo=222802560555</link><description>&lt;b&gt;빅데이터&lt;/b&gt;전문가 커리큘럼에서 다루고 있는 내용들은 1) 데이터 분석과 해석, 2) R 프로그램, 3) 요인 및 행렬, 4) 배열 및 리스트, 5) 패키지 등으로 구분해 볼 수 있는데요. 필요한 내용은 알차게 모두 구성되어 있는... </description><bloggername>나날</bloggername><bloggerlink>https://blog.naver.com/kmin4015</bloggerlink><postdate>20220707</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;전문가 꼼꼼한 학습 노하우</title><link>https://blog.naver.com/dbsrptkdgod?Redirect=Log&amp;logNo=222803100328</link><description>&lt;b&gt;빅데이터&lt;/b&gt;전문가 강의에서 다루고 있는 내용들은 1) 해석과 분석, 2) 프로그램 실행, 3) 데이터의 구분 및 유형, 4) 요인 및 행렬, 5) 패키지 등이 있었는데요. 전체적인 내용을 듣고 숙지한 다음에, 개념적인 부분은... </description><bloggername>나</bloggername><bloggerlink>https://blog.naver.com/dbsrptkdgod</bloggerlink><postdate>20220707</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;전문가 대비하는 핵심 노하우</title><link>https://blog.naver.com/zkfk1116?Redirect=Log&amp;logNo=222803090088</link><description>과정에서 다루고 있는 내용들은 1) &lt;b&gt;빅데이터&lt;/b&gt;란?, 2) R 프로그램, 3) 벡터, 4) 데이터 등으로 나누어볼 수 있는데요. 생각했던 것 보다 적은 강의 수 였지만 필요한 내용이 알차게 구성되어 있는 조건이라서 커리큘럼... </description><bloggername>실버푸들아미</bloggername><bloggerlink>https://blog.naver.com/zkfk1116</bloggerlink><postdate>20220707</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;학원 이젠 AWS클라우드까지 체계적으로!</title><link>https://blog.naver.com/jeongok8602?Redirect=Log&amp;logNo=222706245644</link><description>그만큼 계절의 변화가 뚜렷하게 나타나고 있는 지금은 &lt;b&gt;빅데이터&lt;/b&gt; 관련 분야로 취업을 하고 1년차로... 부분은 데이터베이스의 분석이라고 할 수 있는데 여기서 배우는 프로그램이 파이썬을 배우고 프론트엔드에... </description><bloggername>호박공주맘의 시시콜콜</bloggername><bloggerlink>https://blog.naver.com/jeongok8602</bloggerlink><postdate>20220420</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt; 자격증 준비 노하우와 활용 과정</title><link>https://blog.naver.com/sweety4338?Redirect=Log&amp;logNo=222782751481</link><description>정의, &lt;b&gt;빅 데이터&lt;/b&gt; 필요성, 구성과 범위, 데이터 활용의 의미, R 프로그래밍 기본과 같이 &lt;b&gt;빅데이터&lt;/b&gt;자격증 학습할 때 기본적인 것들을 배우기 시작합니다 처음에는 따라가기 어렵기도 했지만, 소수 정예 수업에 한... </description><bloggername>MY 지식@</bloggername><bloggerlink>https://blog.naver.com/sweety4338</bloggerlink><postdate>20220621</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;자격증 활용 방법 및 공부 팁</title><link>https://blog.naver.com/hjjkr?Redirect=Log&amp;logNo=222803875339</link><description>마케팅 업무를 하는 분들이라면 &lt;b&gt;빅데이터&lt;/b&gt;의 중요성에 대해서 공감하실 수 있을 것 같아요. 실제 관련... 산적해 있는 각종 데이터들을 수집, 분석 및 통계를 내어 이를 가지고 기업의 이익이 될 수 있도록 도움을... </description><bloggername>원주불곰댁 꼼지락 하우스</bloggername><bloggerlink>https://blog.naver.com/hjjkr</bloggerlink><postdate>20220708</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt; 교육 단계별 맞춤형 학습과정</title><link>https://blog.naver.com/dorothy2648?Redirect=Log&amp;logNo=222756586083</link><description>통해 &lt;b&gt;빅데이터&lt;/b&gt; 교육에 대해 알게 되었습니다 이러한 이류로 여러 가지 기술에 대해서 알아보았고, 그 중에서도 가장 관심 있고 예전부터 취득하고 싶었던 &lt;b&gt;빅데이터&lt;/b&gt; 분석기사를 따 보려고 계획을 세웠습니다... </description><bloggername>오즈미니</bloggername><bloggerlink>https://blog.naver.com/dorothy2648</bloggerlink><postdate>20220602</postdate></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;자격증 취득을 목표로 한 분석방법</title><link>https://blog.naver.com/gywls5012?Redirect=Log&amp;logNo=222808899184</link><description>필요한 데이터만 모아서 사람들이 원하는 것을 뽑아낼 수 있는 능력을 가지고 싶었죠. 제가 앞으로 사회에 나가서 취직을 하는 것에 큰 도움을 받을 수 있을 것 같아서 합격률이 40% 정도인 &lt;b&gt;빅데이터&lt;/b&gt; 시험 취득... </description><bloggername>원두커피전국최저가판매/세보커피머신수리as전문</bloggername><bloggerlink>https://blog.naver.com/gywls5012</bloggerlink><postdate>20220712</postdate></item></channel></rss>

In [5]:
import warnings
warnings.filterwarnings('ignore')
from bs4 import BeautifulSoup
xml = response_body.decode('utf-8')
bs = BeautifulSoup(xml,'lxml')
bs.get_text()

"Naver Open API - blog ::'빅데이터'https://search.naver.comNaver Search ResultThu, 28 Jul 2022 10:39:29 +09001144657110<b>빅데이터</b>전문가 준비를 위한 체계적인 방법https://blog.naver.com/nam8853nam?Redirect=Log&logNo=222802704648그 중에서도 주목해 볼만한 분야가 바로 ‘<b>빅데이터</b>’ 라고 생각했어요. 기업이 이익을 창출하기... 이런 점들을 고려했을 때 1) 영업, 2) 컨설팅, 3) 제조 분야 모두 통틀어서 데이터 분석이 정말 중요한 부분을... 율맘 스토리https://blog.naver.com/nam8853nam20220707<b>빅데이터</b>분석기사 실기 준비를 위한 학습루틴https://blog.naver.com/parkrapp?Redirect=Log&logNo=222753783578안녕하세요, 오늘은 제가 도전한 <b>빅데이터</b>분석기사에 대한 정보를 많은 분과 나누고 싶어 이야기를... <b>빅데이터</b>를 이해하고 이를 분석, 수집, 저장 등의 시각화를 수행하는 실무자 역할을 하는 분석기사는... 황금빛 쭈롱월드https://blog.naver.com/parkrapp20220531<b>빅데이터</b>전문가 공부했던 과정https://blog.naver.com/kmin4015?Redirect=Log&logNo=222802560555<b>빅데이터</b>전문가 커리큘럼에서 다루고 있는 내용들은 1) 데이터 분석과 해석, 2) R 프로그램, 3) 요인 및 행렬, 4) 배열 및 리스트, 5) 패키지 등으로 구분해 볼 수 있는데요. 필요한 내용은 알차게 모두 구성되어 있는... 나날https://blog.naver.com/kmin401520220707<b>빅데이터</b>전문가 꼼꼼한 학습 노하우https://blog.naver.com/dbsrptkdgod?Redirect=Log&logNo=222803100328<b>빅데이터</b>전문가 강의에서 다루고 있는 내용들은 1) 해석과 분석, 2) 프로그램 실행, 3) 데이터의 구분 및 유형, 4) 요인 및 행렬, 5) 패키지 등이 있었는데요. 전체적인 내용을 듣고 숙지한 다음에, 개념적인 부분은... 나https://blog.naver.com/dbsrptkdgod20220707<b>빅데이터</b>전문가 대비하는 핵심 노하우https://blog.naver.com/zkfk1116?Redirect=Log&logNo=222803090088과정에서 다루고 있는 내용들은 1) <b>빅데이터</b>란?, 2) R 프로그램, 3) 벡터, 4) 데이터 등으로 나누어볼 수 있는데요. 생각했던 것 보다 적은 강의 수 였지만 필요한 내용이 알차게 구성되어 있는 조건이라서 커리큘럼... 실버푸들아미https://blog.naver.com/zkfk111620220707<b>빅데이터</b>학원 이젠 AWS클라우드까지 체계적으로!https://blog.naver.com/jeongok8602?Redirect=Log&logNo=222706245644그만큼 계절의 변화가 뚜렷하게 나타나고 있는 지금은 <b>빅데이터</b> 관련 분야로 취업을 하고 1년차로... 부분은 데이터베이스의 분석이라고 할 수 있는데 여기서 배우는 프로그램이 파이썬을 배우고 프론트엔드에... 호박공주맘의 시시콜콜https://blog.naver.com/jeongok860220220420<b>빅데이터</b> 자격증 준비 노하우와 활용 과정https://blog.naver.com/sweety4338?Redirect=Log&logNo=222782751481정의, <b>빅 데이터</b> 필요성, 구성과 범위, 데이터 활용의 의미, R 프로그래밍 기본과 같이 <b>빅데이터</b>자격증 학습할 때 기본적인 것들을 배우기 시작합니다 처음에는 따라가기 어렵기도 했지만, 소수 정예 수업에 한... MY 지식@https://blog.naver.com/sweety433820220621<b>빅데이터</b>자격증 활용 방법 및 공부 팁https://blog.naver.com/hjjkr?Redirect=Log&logNo=222803875339마케팅 업무를 하는 분들이라면 <b>빅데이터</b>의 중요성에 대해서 공감하실 수 있을 것 같아요. 실제 관련... 산적해 있는 각종 데이터들을 수집, 분석 및 통계를 내어 이를 가지고 기업의 이익이 될 수 있도록 도움을... 원주불곰댁 꼼지락 하우스https://blog.naver.com/hjjkr20220708<b>빅데이터</b> 교육 단계별 맞춤형 학습과정https://blog.naver.com/dorothy2648?Redirect=Log&logNo=222756586083통해 <b>빅데이터</b> 교육에 대해 알게 되었습니다 이러한 이류로 여러 가지 기술에 대해서 알아보았고, 그 중에서도 가장 관심 있고 예전부터 취득하고 싶었던 <b>빅데이터</b> 분석기사를 따 보려고 계획을 세웠습니다... 오즈미니https://blog.naver.com/dorothy264820220602<b>빅데이터</b>자격증 취득을 목표로 한 분석방법https://blog.naver.com/gywls5012?Redirect=Log&logNo=222808899184필요한 데이터만 모아서 사람들이 원하는 것을 뽑아낼 수 있는 능력을 가지고 싶었죠. 제가 앞으로 사회에 나가서 취직을 하는 것에 큰 도움을 받을 수 있을 것 같아서 합격률이 40% 정도인 <b>빅데이터</b> 시험 취득... 원두커피전국최저가판매/세보커피머신수리as전문https://blog.naver.com/gywls501220220712"

#### json으로 가져오기

In [223]:
# 네이버 검색 API예제는 블로그를 비롯 전문자료까지 호출방법이 동일하므로 blog검색만 대표로 예제를 올렸습니다.
# 네이버 검색 Open API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
url = "https://openapi.naver.com/v1/search/blog?query=" + query # json 결과
#url = "https://openapi.naver.com/v1/search/blog.xml?query=" + query # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
df = pd.read_json(response_body.decode('utf-8'))
df

검색감자
{
	"lastBuildDate":"Thu, 28 Jul 2022 20:28:13 +0900",
	"total":9359197,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"<b>감자<\/b>조림 만드는 법 백종원 간장<b>감자<\/b>조림 레시피 반찬거리",
			"link":"https:\/\/blog.naver.com\/mijinkim80?Redirect=Log&logNo=222826703484",
			"description":"<b>감자<\/b>조림 만드는 법 찜닭 맛이 나는 백종원 간장<b>감자<\/b>조림 레시피 국물과 함께 밥에 올려 비벼 먹으면 꿀맛이에요 요즘 <b>감자<\/b>반찬 정말 많이 해 드시죠? 사진첩 정리하다 나온, 맛에 비해 사진이 안 따라주는... ",
			"bloggername":"MJ의후다닥레시피~♥",
			"bloggerlink":"https:\/\/blog.naver.com\/mijinkim80",
			"postdate":"20220724"
		},
		{
			"title":"강아지 삶은 <b>감자<\/b> 효능!생으로 먹이면 위험한 이유",
			"link":"https:\/\/blog.naver.com\/yoonsu3454?Redirect=Log&logNo=222824886237",
			"description":"안녕하세요 강아지 행동교정 전문가 공인 1등 애견훈련사 조재호입니다 <b>감자<\/b>는 오래전부터 먹을게 많이 없었던 우리나라 조상님들의 허기를 채워줄수 있는 최고의 영양 간식으로써 요즘에도 <b>감자<\/b>를 삶아서... ",
			"bloggername":"조재호훈련사 강아지 행동교정 반려견 방문교육",
			"bloggerlink":"https:\/\/blog.naver.com\/yoonsu3454",
			"postdate":"20220722"
		},
		{
			"title":"<b>감자<\/b>샐러드 맛있는 계란<b>감자<\/b> 샌드위치 만들기",
			"link":"https:\/\/blog.naver.com\/yee1036?Redirect=Log&logNo=222825326304",
			"description":"<b>감자<\/b>샐러드 맛있는 계란<b>감자<\/b> 샌드위치 만들기 오늘은 시댁 조부모님 제삿날이라 하루 종일 시댁 주방에서 열 일할 똥썹맘인데요. 하아~ 아버님도 형제들 중 셋째시고 저도 둘째 며느리인데 이건 뭔가 쫌..... ",
			"bloggername":"똥썹모친의 맛이야기",
			"bloggerlink":"https:\/\/blog.naver.com\/yee1036",
			"postdate":"20220723"
		},
		{
			"title":"간장<b>감자<\/b>조림 쫀득한 아기 <b>감자<\/b>조림 만드는 법 간단한 아이반찬",
			"link":"https:\/\/blog.naver.com\/bongs1021?Redirect=Log&logNo=222824346108",
			"description":"간장<b>감자<\/b>조림 만들 때 식감을 포슬포슬할 것인가, 쫀득하게 할 것인가에 따라 양념과 양념 넣는 순서가 달라진다. 아기 <b>감자<\/b>조림 만드는 법으로는 쫀득한 <b>감자<\/b>조림 레시피가 인기가 좋다. 쫀득한 식감으로... ",
			"bloggername":"봉스, 여자의 부엌",
			"bloggerlink":"https:\/\/blog.naver.com\/bongs1021",
			"postdate":"20220722"
		},
		{
			"title":"계란 <b>감자<\/b>샐러드 만들기 맛있는 <b>감자<\/b> 샌드위치 만들기",
			"link":"https:\/\/blog.naver.com\/ssieie?Redirect=Log&logNo=222826144894",
			"description":"계란 <b>감자<\/b>샐러드 만들기 <b>감자<\/b>샌드위치 만들기 <b>감자<\/b>샐러드 샌드위치 만들기 <b>감자<\/b>가 참 맛있는 계절~ 오늘은 샐러드로 만들어 보았어요 내친김에 모닝빵 꺼내 샌드위치도 뚝딱!! 특히 저희 아빠가 너무너무... ",
			"bloggername":"알콩&apos;s sweet factory",
			"bloggerlink":"https:\/\/blog.naver.com\/ssieie",
			"postdate":"20220724"
		},
		{
			"title":"계란 <b>감자<\/b>샐러드 만들기 으깬<b>감자<\/b>요리 아이간식... ",
			"link":"https:\/\/blog.naver.com\/psy9133?Redirect=Log&logNo=222822365767",
			"description":"계란<b>감자<\/b>샐러드 만들기 으깬 <b>감자<\/b>요리 아이간식 계란<b>감자<\/b> 샌드위치만들기 <b>감자<\/b> 1개 손질 후 125g 삶은계란 2개 햄 40g 오이 1\/4개 40g 당근 20g 피클 3~4조각 양파 작은것 1\/6개 30g 마요네즈 (6) - 기호껏 황설탕 (1)... ",
			"bloggername":"은솔희섭mom의 데이바이데이 story~*",
			"bloggerlink":"https:\/\/blog.naver.com\/psy9133",
			"postdate":"20220721"
		},
		{
			"title":"<b>감자<\/b> 삶는법 <b>감자<\/b> 삶는 시간 달짝지근 추억의 맛 <b>감자<\/b>삶기",
			"link":"https:\/\/blog.naver.com\/peace8012?Redirect=Log&logNo=222803723626",
			"description":"<b>감자<\/b>가 한창 제철이지요 햇<b>감자<\/b>니 분도 많이 나고 맛이 좋은 건 당연할 텐데요 이럴 때 삶은감.자 맛을 간식으로 먹어보지 않을 수가 없지요 이맘때가 되면 저는 늘... 할머니가 삶아주신 <b>감자<\/b>가 생각이... ",
			"bloggername":"레즐리의 톡톡한 이야기",
			"bloggerlink":"https:\/\/blog.naver.com\/peace8012",
			"postdate":"20220707"
		},
		{
			"title":"고추장 <b>감자<\/b>조림 만드는 법 밥을 부르는 비법 매운<b>감자<\/b>조림... ",
			"link":"https:\/\/blog.naver.com\/baby0817?Redirect=Log&logNo=222827704337",
			"description":"고추장 <b>감자<\/b>조림 만드는 법 밥을 부르는 매운<b>감자<\/b>조림 일주일 밑반찬 햇<b>감자<\/b>가 한창 맛있는 요즘 츄츄네도 집에 정말 많이 쟁여두고 먹고 있는데요. 조림부터 튀김까지 정말 많은 요리를 해먹고 있습니다.... ",
			"bloggername":"축복받은 유전자 완소남매의 엄마표 먹거리",
			"bloggerlink":"https:\/\/blog.naver.com\/baby0817",
			"postdate":"20220725"
		},
		{
			"title":"<b>감자<\/b>스프 만들기 <b>감자<\/b>요리 간단한 아침메뉴",
			"link":"https:\/\/blog.naver.com\/kimhy004?Redirect=Log&logNo=222805831042",
			"description":"여름에는 맛있는 <b>감자<\/b>가 나와서 <b>감자<\/b>요리를 더 많이 만들게 되는데요. 간단한 아침메뉴로 드시기에 좋은 홍<b>감자<\/b>요리 <b>감자<\/b>스프 레시피 보여드릴게요. 울서방님이랑 함께 먹었는데 너무 맛있다면서 아침메뉴로... ",
			"bloggername":"들꽃향기 건강 밥상",
			"bloggerlink":"https:\/\/blog.naver.com\/kimhy004",
			"postdate":"20220710"
		},
		{
			"title":"<b>감자<\/b> 베이글만들기 (매쉬드포테이토 필링)",
			"link":"https:\/\/blog.naver.com\/dream_hotel?Redirect=Log&logNo=222807576437",
			"description":"Potato bagel 글\/사진 채영이맘 냉장고를 뒤적거리다 보니 있는데 또 구입해서 두 봉지가 된 <b>감자<\/b>들~ <b>감자<\/b>를 좋아하지도 않는데 옥수수도 그닥인데 강원도로 시집간 게 생각할수록 의아하고 자꾸만 챙겨주셔도 왜... ",
			"bloggername":"채영이맘의 달콤스토리",
			"bloggerlink":"https:\/\/blog.naver.com\/dream_hotel",
			"postdate":"20220711"
		}
	]
}

,lastBuildDate,total,start,display,items
0,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '<b>감자</b>조림 만드는 법 백종원 간장<b>감자</b>조림...
1,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '강아지 삶은 <b>감자</b> 효능!생으로 먹이면 위험한 이유'...
2,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '<b>감자</b>샐러드 맛있는 계란<b>감자</b> 샌드위치 만...
3,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '간장<b>감자</b>조림 쫀득한 아기 <b>감자</b>조림 만드...
4,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '계란 <b>감자</b>샐러드 만들기 맛있는 <b>감자</b> 샌...
5,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '계란 <b>감자</b>샐러드 만들기 으깬<b>감자</b>요리 아...
6,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '<b>감자</b> 삶는법 <b>감자</b> 삶는 시간 달짝지근 ...
7,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '고추장 <b>감자</b>조림 만드는 법 밥을 부르는 비법 매운<...
8,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,{'title': '<b>감자</b>스프 만들기 <b>감자</b>요리 간단한 아침메...
9,"Thu, 28 Jul 2022 20:28:13 +0900",9359197,1,10,"{'title': '<b>감자</b> 베이글만들기 (매쉬드포테이토 필링)', 'li..."

#### Q. 네이버 웹문서에서 빅데이터에 대한 데이터를 가져와서 데이터프레임으로 출력하세요.

#### 과제 0728_1

웹문서에서 빅데이터에 대한 의미있는 정보로 구성된 데이터프레임을 출력하세요.

In [71]:
import os
import sys
import urllib.request
client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input("검색")) # 검색할 단어
url = 'https://openapi.naver.com/v1/search/webkr.json?query='+query # json 결과
# url = "https://openapi.naver.com/v1/search/webkr.json?query=" +qurey # xml 결과


request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    #print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

import warnings
warnings.filterwarnings('ignore')
import pandas as pd

df = pd.read_json(response_body.decode('utf-8'))
df

검색코로나

,lastBuildDate,total,start,display,items
0,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,"{'title': '<b>코로나</b>바이러스감염증-19', 'link': 'htt..."
1,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,"{'title': '<b>코로나</b>바이러스감염증-19 - 나무위키', 'link..."
2,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,{'title': '<b>코로나</b>바이러스-19 국내현황 | 다음뉴스 - 미디어...
3,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,"{'title': '<b>코로나</b>19(COVID-19) 실시간 상황판', 'l..."
4,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,{'title': '시도별 발생동향 &lt; 발생동향 &lt; <b>코로나</b>바...
5,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,"{'title': '<b>코로나</b> - 나무위키', 'link': 'https:..."
6,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,"{'title': '발생동향 | 서울특별시', 'link': 'https://www..."
7,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,"{'title': '<b>코로나</b> 라이브 | 실시간 확진자 현황', 'link..."
8,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,{'title': '보건/건강 &gt; <b>코로나</b>19 &gt; <b>코로나...
9,"Thu, 28 Jul 2022 17:39:04 +0900",209117656,1,10,{'title': '<b>코로나</b>19 팩트 &amp; 이슈체크 &lt; 뉴스 ...

In [208]:
import os
import sys
import urllib.request
client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"
encText = urllib.parse.quote("빅데이터")
url = 'https://openapi.naver.com/v1/search/webkr.json?query='+encText # json 결과
# url = "https://openapi.naver.com/v1/search/webkr.json?query=" + encText # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()

import json
if(rescode==200):
    response_body = response.read()
    data = json.loads(response_body)
    response_body.decode('utf-8')
else:
    print("Error Code:" + rescode)
    
    
length = len(data['items'])
title=[]
link=[]
description=[]
for i in range(length):
    title.append(data['items'][i]["title"])
    description.append(data['items'][i]["description"])
    link.append(data['items'][i]["link"])

df = pd.DataFrame({"title":title,"description":description,"link":link})
# df = pd.read_json(response_body.decode('utf-8'))
df

,title,description,link
0,<b>빅 데이터</b> 프로세싱 - 나무위키,Big data processing 디지털 시대에서 폭증하는 '방대한 양의 <b>데...,https://namu.wiki/w/%EB%B9%85%20%EB%8D%B0%EC%9...
1,<b>빅데이터</b>란? | 고급 <b>빅데이터</b> 분석 | SAP Insights,비즈니스에 대한 360도 통찰을 제공하고 디지털 노이즈 속에 숨은 성장 기회를 찾도...,https://www.sap.com/korea/insights/what-is-big...
2,<b>빅 데이터</b>란 무엇입니까? | Oracle 대한민국,<b>빅데이터</b>는 특히 새로운 <b>데이터</b> 소스에서 나온 더 크고 더 ...,https://www.oracle.com/kr/big-data/what-is-big...
3,"<b>빅데이터</b>(big data) 이해 - 정의, 분석, 기술, 특징, 사례 연구",<b>빅데이터</b>(big data)란 기존 <b>데이터</b> 프로세싱 방식을 ...,https://www.redhat.com/ko/topics/big-data
4,네이버 <b>데이터</b>랩,"네이버의 검색 트렌드 및 급상승검색어 이력, 쇼핑 카테고리별 검색 트렌드 제공",https://datalab.naver.com/
5,<b>빅데이터</b> - BC카드,"fnbigdata.com <b>빅데이터</b> 생태계 조성 기반 마련, <b>빅데이...",https://www.bccard.com/card/html/company/kr/bi...
6,트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>빅데이터</b> - ...,"'+getMessage('button.close')+'국가정보, 시장정보, 해외시장...",https://www.kotra.or.kr/bigdata/guide
7,국가기술 <b>빅데이터</b> 분석기사 - <b>데이터</b>자격시험,"정형, 반정형, 비정형 등 다양한 형태의 <b>데이터</b>를 읽을 수 있다. 필요...",https://www.dataq.or.kr/www/sub/a_07.do
8,"<b>빅데이터</b>의 이해 - 글이 작품이 되는 공간, 브런치",<b>빅데이터</b>의 등장 디지털 경제가 확산되면서 아날로그 경제와는 비교가 되지...,https://brunch.co.kr/@linecard/319
9,미디어백과: <b>빅데이터</b> - 네이버 지식백과,미디어백과: <b>빅데이터</b>에 관한 정보 제공,https://terms.naver.com/list.nhn?cid=42183&cat...

In [110]:
import re

for i in range(len(df)):
    df['title'][i] = re.sub("<.*>",'',df['title'][i])
    df['description'][i] = re.sub("<.*>",'',df['description'][i])
    df['link'][i] = re.sub("<.*>",'',df['link'][i])
df

,title,description,link
0,프로세싱 - 나무위키,Big data processing 디지털 시대에서 폭증하는 '방대한 양의 (big...,https://namu.wiki/w/%EB%B9%85%20%EB%8D%B0%EC%9...
1,분석 | SAP Insights,비즈니스에 대한 360도 통찰을 제공하고 디지털 노이즈 속에 숨은 성장 기회를 찾도...,https://www.sap.com/korea/insights/what-is-big...
2,란 무엇입니까? | Oracle 대한민국,"의 이점, 과제 및 모범 사례 외에도 정의 및 역사에 대해 알아보세요.",https://www.oracle.com/kr/big-data/what-is-big...
3,"(big data) 이해 - 정의, 분석, 기술, 특징, 사례 연구","의 정의, 특징, 사례를 설명합니다.",https://www.redhat.com/ko/topics/big-data
4,네이버 랩,"네이버의 검색 트렌드 및 급상승검색어 이력, 쇼핑 카테고리별 검색 트렌드 제공",https://datalab.naver.com/
5,- BC카드,fnbigdata.com 협력 네트워킹 통합 지원 공안 운영시간 : 평일 오전 9...,https://www.bccard.com/card/html/company/kr/bi...
6,트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자 - 코트라 무역투자 24,"'+getMessage('button.close')+'국가정보, 시장정보, 해외시장...",https://www.kotra.or.kr/bigdata/guide
7,국가기술 자격시험,"정형, 반정형, 비정형 등 다양한 형태의 의 범위를 표준화 또는 정규화를 통해 일치...",https://www.dataq.or.kr/www/sub/a_07.do
8,"의 이해 - 글이 작품이 되는 공간, 브런치","가 쏟아지고 있습니다. 매 1 분 동안 구글은 200만 건의 검색 결과, 유튜브는 ...",https://brunch.co.kr/@linecard/319
9,미디어백과: - 네이버 지식백과,미디어백과: 에 관한 정보 제공,https://terms.naver.com/list.nhn?cid=42183&cat...

In [66]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
df = pd.read_json(response_body.decode('utf-8'))
df

,lastBuildDate,total,start,display,items
0,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,"{'title': '<b>빅 데이터</b> 프로세싱 - 나무위키', 'link': ..."
1,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,{'title': '<b>빅데이터</b>란? | 고급 <b>빅데이터</b> 분석 |...
2,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,{'title': '<b>빅 데이터</b>란 무엇입니까? | Oracle 대한민국'...
3,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,"{'title': '<b>빅데이터</b>(big data) 이해 - 정의, 분석, ..."
4,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,"{'title': '네이버 <b>데이터</b>랩', 'link': 'https://..."
5,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,"{'title': '<b>빅데이터</b> - BC카드', 'link': 'https..."
6,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,{'title': '트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>...
7,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,{'title': '국가기술 <b>빅데이터</b> 분석기사 - <b>데이터</b>자...
8,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,"{'title': '<b>빅데이터</b>의 이해 - 글이 작품이 되는 공간, 브런치..."
9,"Thu, 28 Jul 2022 17:29:17 +0900",38500807,1,10,"{'title': '미디어백과: <b>빅데이터</b> - 네이버 지식백과', 'li..."

#### 과제 0728_2

뉴스, 영화, 쇼핑, 지식in, 카페글에서 적합한 주제에 대한 데이터를 가져와서 데이터프레임으로 출력하세요.

In [229]:
# 뉴스
import os
import sys
import urllib.request
client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
url = "https://openapi.naver.com/v1/search/blog?query=" + query # json 결과
#url = "https://openapi.naver.com/v1/search/blog.xml?query=" + query # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    data = json.loads(response_body)
    #print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

#df = pd.read_json(response_body.decode('utf-8'))

length = len(data['items'])
title=[]
link=[]
description=[]
for i in range(length):
    title.append(data['items'][i]["title"])
    description.append(data['items'][i]["description"])
    link.append(data['items'][i]["link"])

df = pd.DataFrame({"title":title,"description":description,"link":link})
# df = pd.read_json(response_body.decode('utf-8'))
df

검색코로나

,title,description,link
0,<b>코로나</b> 확진 증상 변화 및 자가격리 일주일 일기,<b>코로나</b>19 발생 후 2년 반 동안 잘 피해왔다고 생각했는데 지난 8일 ...,https://blog.naver.com/barbieone?Redirect=Log&...
1,<b>코로나</b> 확진 격리중 증상일기(7/25~7/31),#<b>코로나</b>증상 #격리일기 생생후기 올려달라는 칭긔님의 요청에 의해 써봅니...,https://blog.naver.com/kyj1992kr?Redirect=Log&...
2,<b>코로나</b> 확진과 그 증상들 7일간의 격리중 1일차 부터 3일차까지,"나에게는 일어나지 않을것만 같았던 <b>코로나</b> 확진, 지난 토요일부터 증상이...",https://blog.naver.com/roynim2000?Redirect=Log...
3,"<b>코로나</b> 감염, 팍스로비드 처방",성남문화원에서는 해마다 백일장을 개최하는 모양인데 <b>코로나</b> 때문에 온라인...,https://blog.naver.com/fireflybugs?Redirect=Lo...
4,|7월 셋째 주| 한국 방문 중 <b>코로나</b> 걸려서 일주일 자가격리한...,군산 여행을 다녀와서 <b>코로나</b>에 걸려버렸다. 언제 어디서 <b>코로나</...,https://blog.naver.com/stream0929?Redirect=Log...
5,성남시 <b>코로나</b>검사(신속항원검사) 후...,<b>코로나</b>가 다시 기승을 부리고 있지만 신속항원검사로 바뀐 후 <b>코로나...,https://blog.naver.com/cumung?Redirect=Log&log...
6,<b>코로나</b>19 경제회복 특례보증 소상공인 대상 신청(최대 3억원),<b>코로나</b>19로 인한 피해 회복이 아직도 굉장히 더딘 상태입니다. 그 이유...,https://blog.naver.com/topjoys?Redirect=Log&lo...
7,<b>코로나</b> 병상 일지,<b>코로나</b>라고 생각도 못 했던 터라 격리하는 동안 집에 먹을 게 없어서 마...,https://blog.naver.com/wlsdl1000?Redirect=Log&...
8,<b>코로나</b> 확진자의 일주일,<b>코로나</b> 확진자가 되었다. 분명 얼마 전 회사 건강검진 때도 <b>코로나...,https://blog.naver.com/dajung9167?Redirect=Log...
9,[청주보이차] 보이차가 <b>코로나</b> 미치는 영향,남일같던 <b>코로나</b>를 겪고 일상으로 복귀했어요 긴가민가 하던차에 발을 다쳐...,https://blog.naver.com/moka3076?Redirect=Log&l...

In [230]:
# 영화
import os
import sys
import urllib.request
client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
url = "https://openapi.naver.com/v1/search/blog?query=" + query # json 결과
#url = "https://openapi.naver.com/v1/search/blog.xml?query=" + query # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    data = json.loads(response_body)
    #print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

#df = pd.read_json(response_body.decode('utf-8'))

length = len(data['items'])
title=[]
link=[]
description=[]
for i in range(length):
    title.append(data['items'][i]["title"])
    description.append(data['items'][i]["description"])
    link.append(data['items'][i]["link"])

df = pd.DataFrame({"title":title,"description":description,"link":link})
# df = pd.read_json(response_body.decode('utf-8'))
df

검색탑건

,title,description,link
0,영화 <b>탑건</b> 2 매버릭 4DX 리뷰 페니 딸 아멜리아!,<b>탑건</b> 매버릭 4d로 보는 건 여전히 유효한 CGV 지점들이 많다. 수원...,https://blog.naver.com/dongi0508?Redirect=Log&...
1,EP.06 <b>탑건</b>2에서 감명받은 직업관련 태도,준비하던 시험이 끝나고 <b>탑건</b> 2을 보고 왔다. <b>탑건</b> 2는 ...,https://blog.naver.com/dtt9080?Redirect=Log&lo...
2,"<b>탑건</b> 4DX 관람 후기 용산 아이파크몰 직접 비행하는 실감,효과...",# 이 포스팅은 <b>탑건</b> 4DX의 효과에 대해 설명하고 있으니 효과에 대한...,https://blog.naver.com/vivakoreaa?Redirect=Log...
3,<b>탑건</b>1 줄거리 OTT OST 정보 : 전설적인 파일럿 매버릭(톰...,29 재개봉 전 세계에서 흥행 가도를 달리는 톰 크루즈 주연의 영화 &lt;<b>탑...,https://blog.naver.com/psj29351?Redirect=Log&l...
4,<b>탑건</b>: 매버릭 리뷰,12시에 <b>탑건</b>을 보러갔다. <b>탑건</b>이라는 제목 자체를 요즘에 ...,https://blog.naver.com/red1336?Redirect=Log&lo...
5,<b>탑건</b> 메버릭 리뷰(feat. 4dx) 마하 10의 속도로~~!!,1986년 우리 아빠가 나보다 어렸을 적에 <b>탑건</b> 1편이 개봉했었다. <...,https://blog.naver.com/0109lch?Redirect=Log&lo...
6,롯데시네마 <b>탑건</b> 매버릭 62년생 톰크루즈 혼자 다해먹는...,#<b>탑건</b>주인공 #톰크루즈 가 제작자 이름에 올라와 있더라. (거의 심야영...,https://blog.naver.com/niceyiking37?Redirect=L...
7,안타까움과 <b>탑건</b>,지난 금요일엔 우리 선생님과 <b>탑건</b>을 봤는데 옛추억에 즐겁게 보시지 않을...,https://blog.naver.com/vali?Redirect=Log&logNo...
8,<b>탑건</b> 매버릭 전투기보다 중요한 이것?(스포주의),You can be my wingman anytime <b>탑건</b> 매버릭 영화...,https://blog.naver.com/rsupport?Redirect=Log&l...
9,[영화] 노력하는 것도 괜찮은 삶의 방식 - &lt;<b>탑건</b>: 매버릭&gt;,되었다는 건 아닙니다. 묵묵히 자기 자리에서 노력하는 사람이 그만큼의 대접을 받지 ...,https://blog.naver.com/digitalhippy?Redirect=L...

In [247]:
# 쇼핑
import os
import sys
import urllib.request
import json

client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
url = "https://openapi.naver.com/v1/search/shop.json?query=" + query # json 결과

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    data = json.loads(response_body)
    #print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

#df = pd.read_json(response_body.decode('utf-8'))

length = len(data['items'])
title=[]
link=[]
mallName=[]
for i in range(length):
    title.append(data['items'][i]["title"])
    mallName.append(data['items'][i]["mallName"])
    link.append(data['items'][i]["link"])

df = pd.DataFrame({"title":title,"mallName":mallName,"link":link})
# df = pd.read_json(response_body.decode('utf-8'))
df

검색운동화

,title,mallName,link
0,나이키 레볼루션6 넥스트 네이처 런닝화 DC3728-003,네이버,https://search.shopping.naver.com/gate.nhn?id=...
1,나이키 에어맥스 97 트리플화이트 921826-101,네이버,https://search.shopping.naver.com/gate.nhn?id=...
2,아디다스 런닝화 갤럭시 5 FW5717,네이버,https://search.shopping.naver.com/gate.nhn?id=...
3,나이키 에어맥스 엑시스 AA2146-100,네이버,https://search.shopping.naver.com/gate.nhn?id=...
4,뉴발란스 530 스틸그레이 MR530KA,네이버,https://search.shopping.naver.com/gate.nhn?id=...
5,뉴발란스 남여공용 <b>운동화</b> MR530SG,네이버,https://search.shopping.naver.com/gate.nhn?id=...
6,휠라 <b>운동화</b> 레인져 1RM01141D-147,네이버,https://search.shopping.naver.com/gate.nhn?id=...
7,위크나인 니트그램,네이버,https://search.shopping.naver.com/gate.nhn?id=...
8,아디다스 갤럭시 5 G55778,네이버,https://search.shopping.naver.com/gate.nhn?id=...
9,나이키 남성 에어맥스 2017 <b>운동화</b> 849559-001,네이버,https://search.shopping.naver.com/gate.nhn?id=...

In [249]:
# 지식in
import os
import sys
import urllib.request
import json

client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
url = "https://openapi.naver.com/v1/search/kin.json?query=" + query # json 결과

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    data = json.loads(response_body)
    #print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

#df = pd.read_json(response_body.decode('utf-8'))

length = len(data['items'])
title=[]
link=[]
description=[]
for i in range(length):
    title.append(data['items'][i]["title"])
    description.append(data['items'][i]["description"])
    link.append(data['items'][i]["link"])

df = pd.DataFrame({"title":title,"description":description,"link":link})
# df = pd.read_json(response_body.decode('utf-8'))
df

검색강아지

,title,description,link
0,사회화가 안된 <b>강아지</b>,사회화가 안된 <b>강아지</b> <b>강아지</b>가 사람이나 산책 나가서 다른 ...,https://kin.naver.com/qna/detail.naver?d1id=8&...
1,수원<b>강아지</b>분양 도움좀요!!,수원<b>강아지</b>분양 받으려고 알아보고 있는데요 예전에 친구따라서 분양샵......,https://kin.naver.com/qna/detail.naver?d1id=10...
2,<b>강아지</b> 요로결석,저희집 <b>강아지</b>가 요로결석 치료를 두번이나 하고 고생을 한 뒤로 식단 관...,https://kin.naver.com/qna/detail.naver?d1id=8&...
3,<b>강아지</b>가 물리는꿈,오늘 꿈을 꿨는데 요즘 길거리에서 다른 <b>강아지</b>가 물어서 사고 나는 거 ...,https://kin.naver.com/qna/detail.naver?d1id=3&...
4,<b>강아지</b>사료 영양좋은거?,갑자기 <b>강아지</b>를 분양 받아서 키워야 합니다. 그래서 <b>강아지</b>...,https://kin.naver.com/qna/detail.naver?d1id=8&...
5,<b>강아지</b>에 대한것,"... 제 생일 6월 1일에 <b>강아지</b>를 키울건데요, 주인에게 버려진 <b...",https://kin.naver.com/qna/detail.naver?d1id=8&...
6,일산<b>강아지</b>분양 궁금,안녕하세요 저가 이번에 혼자 살게 되서 <b>강아지</b> 한마리를 분양할려고 하는...,https://kin.naver.com/qna/detail.naver?d1id=3&...
7,<b>강아지</b> 집,안녕하세요 학생인데요 시골에 <b>강아지</b> 2마리가 있어요. 근데 <b>강아지...,https://kin.naver.com/qna/detail.naver?d1id=8&...
8,시바 <b>강아지</b> 질문 (내공 100),... 제 <b>강아지</b> 키우는 친구들이 4개월 치고는 너무 크다고합니다.. ...,https://kin.naver.com/qna/detail.naver?d1id=8&...
9,<b>강아지</b> 행동,"제가 <b>강아지</b>, 고양이를 좋아하는데 그래서 동물들의 행동... 그 식당에...",https://kin.naver.com/qna/detail.naver?d1id=8&...

In [251]:
# 카페글
import os
import sys
import urllib.request
import json

client_id = "E2kR3aLCHEN1UsOGUP7R"
client_secret = "gvdT1t2BQa"

query = urllib.parse.quote(input(r"검색")) # 검색할 단어
url = "https://openapi.naver.com/v1/search/cafearticle.json?query=" + query # json 결과

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read() #response_body가 이름
    data = json.loads(response_body)
    #print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

#df = pd.read_json(response_body.decode('utf-8'))

length = len(data['items'])
title=[]
link=[]
description=[]
for i in range(length):
    title.append(data['items'][i]["title"])
    description.append(data['items'][i]["description"])
    link.append(data['items'][i]["link"])

df = pd.DataFrame({"title":title,"description":description,"link":link})
# df = pd.read_json(response_body.decode('utf-8'))
df

검색자동차

,title,description,link
0,피견인<b>자동차</b>(트레일러) 면허의 종류,"안녕하세요 제주초보 입니다 운전면허 제 1종 보통,대형 제 2종 보통 면허를 취득한...",http://cafe.naver.com/boatfish/431941
1,개인사업자<b>자동차</b>리스 빠르고 최저가!,개인사업자<b>자동차</b>리스 빠르고 최저가! 다니던 직장이 아무래도 미래가 불확...,http://cafe.naver.com/k5mania/2543934
2,<b>자동차</b>대출 건수과다 통합될까요,저 지금 신용으로는 아무래도 뭘 받기가 힘든거 같아서 <b>자동차</b>대출로 받아...,http://cafe.naver.com/sosllll/18874
3,<b>자동차</b> 에어컨 냄새 제거 이걸로 잡았어요,그자리에서 친구는 자기가 평소에 쓰는게 있다며 <b>자동차</b> 에어컨 냄새 제거...,http://cafe.naver.com/magic26/1882662
4,<b>자동차</b>보험 자차 인상되나요?,작년초에 <b>자동차</b>사고가 나서 자차수리를 했는데요. <b>자동차</b>보험...,http://cafe.naver.com/srbestclub/475207
5,<b>자동차</b> 냄새제거 가장 빠른 방법?,#<b>자동차</b>냄새제거 날이 덥고 습도가 높으니까 <b>자동차</b> 냄새제거...,http://cafe.naver.com/masanmam/6117556
6,<b>자동차</b>리스 장단점 알아보고 현명하게 이용하자,아마 많은 분들이 성인이 되면 가장 먼저 <b>자동차</b>를 알아보게 된다고 생각...,http://cafe.naver.com/icv14/209998
7,<b>자동차</b> 환급금 조회 알고 계세요?,"감사함을 느끼면서, 저도 도움이 될만한게 뭐가 있을지 하면서 <b>자동차</b> 환...",http://cafe.naver.com/anycard/1199027
8,대전<b>자동차</b>직업전문학교 취업까지 확실하게,대전<b>자동차</b>직업전문학교 취업까지 확실하게 최근 취업을 준비하시는 분들은 ...,http://cafe.naver.com/specup/7037911
9,계기판빨간<b>자동차</b>,"말그대로 계기판에 그림처럼 한3ㅡ4초간 빨간<b>자동차</b>모양이 뜨더라구요, 빨...",http://cafe.naver.com/bimmerwerks/752849

#### 과제 0728_3 

아래사항에 유의하여 OpenWeatherMap 날씨정보를 웹 API로 가져와서 출력하세요
* https://openweathermap.org/api 사이트에서 Current Weather data에 대한 API doc 내용을 파악
* 개발자 등록을 하고 API 키 발급 받음(https://home.openweathermap.org/users/sign_up)
* New Account 등록 후 API Keys라는 탭에서 API Key 확인 가능
* 기본적으로 유료 사이트이지만 현재 날씨, 5일까지의 날씨는 무료로 사용할 수 있음(단 1분에 60번만 호출 가능)
* 서울, 토쿄, 뉴욕의 날씨를 가져오는 프로그램 작성(text로 가져와서 json으로 변환하여 일차 출력)
  - cities = ["Seoul,KR", "Tokyo,JP", "New York,US"]
  - 가져올 정보 : 도시별 날씨(description), 최저 기온(temp_min), 최고 기온(temp_max), 습도(humidity), 기압(pressure), 풍속(speed)
  - 기온 데이터는 켈빈 온도로 되어 있으며 섭씨 온도로 변환해서 출력
* json 포멧으로 출력 데이터를 아래와 같이 가독력 있게 출력(소수점 2번째에서 반올림 처리)

```
+ 도시 = Seoul
| 날씨 = broken clouds
| 최저 기온 = -1.0 2
| 최고 기온 = 2.0 2
| 습도 = 74
| 기압 = 1023
| 풍속 = 0.5
```

In [169]:
import os
import sys
import urllib.request
import json

API_key = '7b4ea05181ecdfc3af4cc9cfeb1c5fa5'
city_name = 'Seoul'
country_code = 'KR'

url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name},{country_code}&appid={API_key}"

request = urllib.request.Request(url)
response = urllib.request.urlopen(request)
rescode = response.getcode()

response_dict = json.loads(response_body.decode('utf-8'))
response_dict

{'coord': {'lon': 126.9778, 'lat': 37.5683},
 'weather': [{'id': 803,
   'main': 'Clouds',
   'description': 'broken clouds',
   'icon': '04d'}],
 'base': 'stations',
 'main': {'temp': 303.56,
  'feels_like': 307.23,
  'temp_min': 300.84,
  'temp_max': 305.81,
  'pressure': 1010,
  'humidity': 62},
 'visibility': 10000,
 'wind': {'speed': 3.09, 'deg': 290},
 'clouds': {'all': 75},
 'dt': 1659003336,
 'sys': {'type': 1,
  'id': 8105,
  'country': 'KR',
  'sunrise': 1658953929,
  'sunset': 1659005087},
 'timezone': 32400,
 'id': 1835848,
 'name': 'Seoul',
 'cod': 200}

In [182]:
print('+ 도시 =',response_dict['name'],'\n'
     '| 날씨 =',response_dict['weather'][0]['description'],'\n'
     '| 최저 기온 =',response_dict['main']['temp_min'],'\n'
     '| 최고 기온 =',response_dict['main']['temp_max'],'\n'
     '| 습도 =',response_dict['main']['humidity'],'\n'
     '| 기압 =',response_dict['main']['pressure'],'\n'
     '| 풍속 =',response_dict['wind']['speed'],'\n')

+ 도시 = Seoul
| 날씨 = broken clouds
| 최저 기온 = 300.84
| 최고 기온 = 305.81
| 습도 = 62
| 기압 = 1010
| 풍속 = 3.09

In [194]:
import os
import sys
import urllib.request
import json

API_key = '7b4ea05181ecdfc3af4cc9cfeb1c5fa5'
city_name = 'Tokyo'
country_code = 'JP'

url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name},{country_code}&appid={API_key}"

request = Request(url)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()

response_dict2 = json.loads(response_body.decode('utf-8'))
response_dict2

{'coord': {'lon': 139.6917, 'lat': 35.6895},
 'weather': [{'id': 501,
   'main': 'Rain',
   'description': 'moderate rain',
   'icon': '10n'}],
 'base': 'stations',
 'main': {'temp': 302.08,
  'feels_like': 306.87,
  'temp_min': 299.15,
  'temp_max': 303.72,
  'pressure': 1015,
  'humidity': 76},
 'visibility': 10000,
 'wind': {'speed': 5.66, 'deg': 200},
 'rain': {'1h': 2.05},
 'clouds': {'all': 75},
 'dt': 1659005916,
 'sys': {'type': 2,
  'id': 2038398,
  'country': 'JP',
  'sunrise': 1658951135,
  'sunset': 1659001779},
 'timezone': 32400,
 'id': 1850144,
 'name': 'Tokyo',
 'cod': 200}

In [197]:
print('+ 도시 =',response_dict2['name'],'\n'
     '| 날씨 =',response_dict2['weather'][0]['description'],'\n'
     '| 최저 기온 =',response_dict2['main']['temp_min'],'\n'
     '| 최고 기온 =',response_dict2['main']['temp_max'],'\n'
     '| 습도 =',response_dict2['main']['humidity'],'\n'
     '| 기압 =',response_dict2['main']['pressure'],'\n'
     '| 풍속 =',response_dict2['wind']['speed'],'\n')

+ 도시 = Tokyo
| 날씨 = moderate rain
| 최저 기온 = 299.15
| 최고 기온 = 303.72
| 습도 = 76
| 기압 = 1015
| 풍속 = 5.66

In [200]:
import os
import sys
import urllib.request
import json

API_key = '7b4ea05181ecdfc3af4cc9cfeb1c5fa5'
city_name = 'New%20York'
country_code = 'US'

url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name},{country_code}&appid={API_key}"

request = Request(url)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()

response_dict3 = json.loads(response_body.decode('utf-8'))
response_dict3

{'coord': {'lon': -74.006, 'lat': 40.7143},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 296.54,
  'feels_like': 297.28,
  'temp_min': 294.73,
  'temp_max': 297.56,
  'pressure': 1011,
  'humidity': 90},
 'visibility': 10000,
 'wind': {'speed': 3.6, 'deg': 180},
 'clouds': {'all': 0},
 'dt': 1659006621,
 'sys': {'type': 2,
  'id': 2039034,
  'country': 'US',
  'sunrise': 1659001728,
  'sunset': 1659053760},
 'timezone': -14400,
 'id': 5128581,
 'name': 'New York',
 'cod': 200}

In [202]:
print('+ 도시 =',response_dict3['name'],'\n'
     '| 날씨 =',response_dict3['weather'][0]['description'],'\n'
     '| 최저 기온 =',response_dict3['main']['temp_min'],'\n'
     '| 최고 기온 =',response_dict3['main']['temp_max'],'\n'
     '| 습도 =',response_dict3['main']['humidity'],'\n'
     '| 기압 =',response_dict3['main']['pressure'],'\n'
     '| 풍속 =',response_dict3['wind']['speed'],'\n')

+ 도시 = New York
| 날씨 = clear sky
| 최저 기온 = 294.73
| 최고 기온 = 297.56
| 습도 = 90
| 기압 = 1011
| 풍속 = 3.6

## 공공데이터 api

### 상가 업소 정보

In [47]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
import json

skey = 'Oa1TugkkNZ8H0%2FNfkzQr3VvFlAFUHW1WM69wVS86NT4dBCVEWpzqkkBJRFEiEL9ggz5wry6mGQitMRGDGISeUg%3D%3D'
res_id = 'storezone'
stype = 'json' #그냥 type은 예약어라 X stype으룽

url = 'http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi'
params = f'?ServiceKey={skey}&type={stype}&resId={res_id}&'+urlencode({quote_plus('key'):'9174'})
query = url + params
print(query)

request = Request(query)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()
#print(response_body)


response_dict = json.loads(response_body.decode('utf-8'))
items = response_dict['body']['items']

df = pd.DataFrame(items)
df

http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi?ServiceKey=Oa1TugkkNZ8H0%2FNfkzQr3VvFlAFUHW1WM69wVS86NT4dBCVEWpzqkkBJRFEiEL9ggz5wry6mGQitMRGDGISeUg%3D%3D&type=json&resId=storezone&key=9174

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9174,인사동,11,서울특별시,11110,종로구,226875,21,MULTIPOLYGON (((126.986059148338 37.5765234907...,2021-06-30

In [48]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
import json

def baro_api(skey,res_id,encode):
    
    stype = 'json'
    url = 'http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi'
    params = f'?ServiceKey={skey}&type={stype}&resId={res_id}&'+ encode
    query = url + params
    
    request = Request(query)
    request.get_method = lambda: 'GET'
    response_body = urlopen(request).read()
    
    response_dict = json.loads(response_body.decode('utf-8'))
    items = response_dict['body']['items']
    df = pd.DataFrame(items)
    return df

### 상권 조회
#### 지정상권 조회

In [49]:
skey = 'Oa1TugkkNZ8H0%2FNfkzQr3VvFlAFUHW1WM69wVS86NT4dBCVEWpzqkkBJRFEiEL9ggz5wry6mGQitMRGDGISeUg%3D%3D'
res_id = 'storezone'
encode = urlencode({quote_plus('key'):'9193'})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9193,동대문역사문화공원역,11,서울특별시,11140,중구,79167,17,MULTIPOLYGON (((127.00304244009 37.56673071604...,2021-06-30

#### 반경내 상권조회

In [50]:
encode = urlencode({quote_plus('catId'):'radius',quote_plus('radius'):'500'
                    ,quote_plus('cx'):'127.004528',quote_plus('cy'):'37.567538'})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9170,동대문시장_1,11,서울특별시,11110,종로구,75046,13,MULTIPOLYGON (((127.00616674831 37.57097429301...,2021-06-30
1,9180,종로5가역_1,11,서울특별시,11110,종로구,44881,9,MULTIPOLYGON (((127.001579474423 37.5708212220...,2021-06-30
2,9192,동대문시장_2,11,서울특별시,11140,중구,60995,18,MULTIPOLYGON (((127.006693001676 37.5694470928...,2021-06-30
3,9193,동대문역사문화공원역,11,서울특별시,11140,중구,79167,17,MULTIPOLYGON (((127.00304244009 37.56673071604...,2021-06-30
4,9206,을지로4가역,11,서울특별시,11140,중구,81565,9,MULTIPOLYGON (((126.998050690253 37.5686092455...,2021-06-30

#### 과제 0728_4 
사각형내 상권조회

In [56]:
skey = 'Oa1TugkkNZ8H0%2FNfkzQr3VvFlAFUHW1WM69wVS86NT4dBCVEWpzqkkBJRFEiEL9ggz5wry6mGQitMRGDGISeUg%3D%3D'
res_id = 'storezone'
    
encode = urlencode({quote_plus('catId'):'rectangle',quote_plus('minx'):'126.978020'
                    ,quote_plus('miny'):'37.557825',quote_plus('maxx'):'126.987732',quote_plus('maxy'):'37.562022'})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9191,남대문시장,11,서울특별시,11140,중구,111020,27,MULTIPOLYGON (((126.976451547074 37.5576325944...,2021-06-30
1,9196,명동역,11,서울특별시,11140,중구,96649,28,MULTIPOLYGON (((126.983476244148 37.5605598377...,2021-06-30

#### 과제 0728_5
행정단위 상권조회

In [57]:
encode = urlencode({quote_plus('catId'):'dong',quote_plus('divId'):'adongCd'
                    ,quote_plus('key'):'1168069000'})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9324,포이사거리,11,서울특별시,11680,강남구,14033,33,MULTIPOLYGON (((127.044811833677 37.4781705036...,2021-06-30

### 상가업소 조회

#### 행정동 단위 상가업소 조회

In [46]:
res_id = 'store'
encode = urlencode({quote_plus('catId'):'dong',quote_plus('divId'):'ctprvnCd',quote_plus('key'):'11'})

baro_api(skey,res_id,encode)

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10001387,이음스튜디오,,D,소매,D18,사진/광학/정밀기기소매,D18A03,카메라판매,G47823,...,1168010700105910014011130,신사동빌딩,서울특별시 강남구 논현로154길 5,135893,06025,,1,,127.028616,37.521818
1,10004623,이철헤어커커,상계역점,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1135010600101410007000001,,서울특별시 노원구 한글비석로20길 43,139220,01662,,2,,127.074146,37.661098
2,10016187,일조산업,,D,소매,D07,가정/주방/인테리어,D07A15,유리/페인트/철물건축자재,G47519,...,1120011500102800040003693,일조산업,서울특별시 성동구 광나루로 290,133120,04796,,,,127.061970,37.547705
3,10030788,장안순대국밥,,Q,음식,Q10,별식/퓨전요리,Q10A05,순대전문점,I56111,...,1123010500105300016018329,,서울특별시 동대문구 고미술로 81,130032,02622,,1,,127.055701,37.565595
4,10031349,장어야,동자동점,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1117010700100350141024265,,서울특별시 용산구 후암로57길 51-3,140821,04324,,,,126.974149,37.551236
5,10031436,장어천국,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010400103720003004086,,서울특별시 서초구 원터4길 3,137150,06806,,2,,127.055836,37.443503
6,10034303,재건공조,,D,소매,D07,가정/주방/인테리어,D07A15,유리/페인트/철물건축자재,G47519,...,1123010300111490017032382,,서울특별시 동대문구 종암로 6,130865,02465,,1,,127.036595,37.590976
7,10034977,재진패션,,D,소매,D05,의복의류,D05A01,일반의류,G47416,...,1162010200114800001003292,계림빌딩,서울특별시 관악구 난곡로57길 11,151894,08771,,2,,126.914212,37.479482
8,10038561,전자랜드프라이스킹,은평점,D,소매,D12,가전제품소매,D12A01,일반가전제품,G47320,...,1138010700101090006000001,,서울특별시 은평구 은평로 122,122010,03454,,1,,126.921329,37.600043
9,10041487,정관장,서대문역점,D,소매,D03,종합소매점,D03B04,시장/종합상가,G47129,...,1141010400101670000029786,로얄빌딩,서울특별시 서대문구 통일로 111,120020,03738,,1,,126.967217,37.564800
10,10041503,정관장,남부법원점,D,소매,D10,건강/미용식품,D10A04,건강식품판매,G47216,...,1147010100110130004003329,성배법조빌딩,서울특별시 양천구 신월로 369,158070,08021,,,,126.861992,37.522403
11,10050747,제시카키친,이대하늬솔점,Q,음식,Q06,양식,Q06A05,패밀리레스토랑,I56114,...,1141011300100850001030936,하늬솔빌딩,서울특별시 서대문구 성산로 527,120160,03721,A,1,,126.944072,37.563766
12,10056742,제일전기조명,,D,소매,D07,가정/주방/인테리어,D07A10,조명기구/전기용품,G47591,...,1111015700100800001014076,,서울특별시 종로구 창경궁로 127,110410,03136,,1,,126.997296,37.573790
13,10065677,종가집설렁탕,,Q,음식,Q01,한식,Q01A09,설렁탕집,I56111,...,1147010100102960077006237,,서울특별시 양천구 신목로 56,158070,08015,,,,126.872936,37.519849
14,10072281,주연테크컴퓨터,신촌점,D,소매,D08,사무/문구/컴퓨터,D08A05,컴퓨터전문매장,G47311,...,1141011000101560034026971,,서울특별시 서대문구 신촌로 249,120821,03774,,,,126.953668,37.557472
15,10075124,준오헤어돈암2호점,돈암2호점,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1129011600100850104000001,,서울특별시 성북구 동소문로22길 39,136051,02845,,2,,127.018438,37.591403
16,10080606,중화공인중개사사무소,,L,부동산,L01,부동산중개,L01A01,부동산중개,L68221,...,1126010300101100018013614,,서울특별시 중랑구 봉화산로 76,131120,02089,,1,,127.082755,37.601606
17,10085207,GS25,용산하얏트점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1117013000102430037009047,,서울특별시 용산구 회나무로44길 46,140200,04346,,1,,126.995255,37.539470
18,10086312,지우미용실신월점,신월점,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1147010300104430005010798,,서울특별시 양천구 오목로 41,158090,07930,,1,,126.842187,37.522183
19,10088738,지혜수산,화곡역점,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,1150010300110680023029683,동인빌딩,서울특별시 강서구 화곡로 119,157010,07711,,,,126.835093,37.540431

In [ ]:
p.67 참고
indsLclsCd : 상권업종 대분류코드
indsLclsNm : 상권업종 대분류명
indsMclsCd : 상권업종 중분류코드
indsSclsCd : 상권업종 소분류코드

ksicCd : 표준산업분류코드